// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbrQ9vRbp-vZCw_4hRzW9KKFZG-kWbv_M',
    appId: '1:452215614779:web:1210c851b4e4a895ed1b1e',
    messagingSenderId: '452215614779',
    projectId: 'ustoz-ai-task',
    authDomain: 'ustoz-ai-task.firebaseapp.com',
    storageBucket: 'ustoz-ai-task.firebasestorage.app',
    measurementId: 'G-6WTG1PDF2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyE0EDtMfrYUMCfvz0X6m6x8nLcLi1gTM',
    appId: '1:452215614779:android:21933b60ae793159ed1b1e',
    messagingSenderId: '452215614779',
    projectId: 'ustoz-ai-task',
    storageBucket: 'ustoz-ai-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7NJq6tud0IE_Kn_K9CPCJiY78IchLqGc',
    appId: '1:452215614779:ios:8baaa13233b26383ed1b1e',
    messagingSenderId: '452215614779',
    projectId: 'ustoz-ai-task',
    storageBucket: 'ustoz-ai-task.firebasestorage.app',
    androidClientId: '452215614779-r0gog98uge8sndd6q60e66k182u3chv9.apps.googleusercontent.com',
    iosClientId: '452215614779-o6fkbmq74d6bmdvdntjm73b076bngbtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ustozAiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7NJq6tud0IE_Kn_K9CPCJiY78IchLqGc',
    appId: '1:452215614779:ios:8baaa13233b26383ed1b1e',
    messagingSenderId: '452215614779',
    projectId: 'ustoz-ai-task',
    storageBucket: 'ustoz-ai-task.firebasestorage.app',
    androidClientId: '452215614779-r0gog98uge8sndd6q60e66k182u3chv9.apps.googleusercontent.com',
    iosClientId: '452215614779-o6fkbmq74d6bmdvdntjm73b076bngbtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ustozAiTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbrQ9vRbp-vZCw_4hRzW9KKFZG-kWbv_M',
    appId: '1:452215614779:web:51bb233cfeb478dfed1b1e',
    messagingSenderId: '452215614779',
    projectId: 'ustoz-ai-task',
    authDomain: 'ustoz-ai-task.firebaseapp.com',
    storageBucket: 'ustoz-ai-task.firebasestorage.app',
    measurementId: 'G-RFPJBGJR2Q',
  );
}
